//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.ServiceContainsConsoleClient.ServiceReferenceContains {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/_02.Contains")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceContains.IServiceContains")]
    public interface IServiceContains {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContains/GetContainNumber", ReplyAction="http://tempuri.org/IServiceContains/GetContainNumberResponse")]
        int GetContainNumber(string value, string searchedInValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContains/GetContainNumber", ReplyAction="http://tempuri.org/IServiceContains/GetContainNumberResponse")]
        System.Threading.Tasks.Task<int> GetContainNumberAsync(string value, string searchedInValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContains/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceContains/GetDataUsingDataContractResponse")]
        _02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType GetDataUsingDataContract(_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceContains/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceContains/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType> GetDataUsingDataContractAsync(_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceContainsChannel : _02.ServiceContainsConsoleClient.ServiceReferenceContains.IServiceContains, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceContainsClient : System.ServiceModel.ClientBase<_02.ServiceContainsConsoleClient.ServiceReferenceContains.IServiceContains>, _02.ServiceContainsConsoleClient.ServiceReferenceContains.IServiceContains {
        
        public ServiceContainsClient() {
        }
        
        public ServiceContainsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceContainsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContainsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceContainsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetContainNumber(string value, string searchedInValue) {
            return base.Channel.GetContainNumber(value, searchedInValue);
        }
        
        public System.Threading.Tasks.Task<int> GetContainNumberAsync(string value, string searchedInValue) {
            return base.Channel.GetContainNumberAsync(value, searchedInValue);
        }
        
        public _02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType GetDataUsingDataContract(_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType> GetDataUsingDataContractAsync(_02.ServiceContainsConsoleClient.ServiceReferenceContains.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
